spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5431/game_store_app_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect